-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.app_departamento
(
    id bigint NOT NULL DEFAULT nextval('app_departamento_id_seq'::regclass),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT app_departamento_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_municipio
(
    id bigint NOT NULL DEFAULT nextval('app_municipio_id_seq'::regclass),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT app_municipio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.app_restaurante
(
    nit integer NOT NULL,
    nombre character varying(70) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    logo character varying(100) COLLATE pg_catalog."default",
    direccion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(15) COLLATE pg_catalog."default" NOT NULL,
    celular character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    departamento_id bigint,
    municipio_id bigint,
    CONSTRAINT app_restaurante_pkey PRIMARY KEY (nit)
);
CREATE TABLE IF NOT EXISTS public.app_cocina
(
    id bigint NOT NULL DEFAULT nextval('app_cocina_id_seq'::regclass),
    usuario character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    restaurante_id integer,
    CONSTRAINT app_cocina_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_caja
(
    id bigint NOT NULL DEFAULT nextval('app_caja_id_seq'::regclass),
    usuario character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    restaurante_id integer,
    CONSTRAINT app_caja_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_mesas
(
    id bigint NOT NULL DEFAULT nextval('app_mesas_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(1) COLLATE pg_catalog."default" NOT NULL,
    restaurante_id integer,
    CONSTRAINT app_mesas_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_mesero
(
    documento character varying(12) COLLATE pg_catalog."default" NOT NULL,
    tipodoc character varying(2) COLLATE pg_catalog."default" NOT NULL,
    nombre1 character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nombre2 character varying(20) COLLATE pg_catalog."default" NOT NULL,
    apellido1 character varying(20) COLLATE pg_catalog."default" NOT NULL,
    apellido2 character varying(20) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(12) COLLATE pg_catalog."default" NOT NULL,
    genero character varying(1) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(30) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    departamento_id bigint,
    municipio_id bigint,
    foto character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT app_mesero_pkey PRIMARY KEY (documento)
);
CREATE TABLE IF NOT EXISTS public.app_estado
(
    id bigint NOT NULL DEFAULT nextval('app_estado_id_seq'::regclass),
    hora_entrada time without time zone,
    hora_salida time without time zone NOT NULL,
    estado character varying(2) COLLATE pg_catalog."default" NOT NULL,
    mesero_id character varying(12) COLLATE pg_catalog."default",
    restaurante_id integer,
    CONSTRAINT app_estado_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_oferta
(
    id bigint NOT NULL DEFAULT nextval('app_oferta_id_seq'::regclass),
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pago character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fecha_publicacion date,
    restaurante_id integer,
    CONSTRAINT app_oferta_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_postulados
(
    id bigint NOT NULL DEFAULT nextval('app_postulados8_id_seq'::regclass),
    fecha date NOT NULL,
    mesero_id character varying(12) COLLATE pg_catalog."default",
    oferta_id bigint,
    CONSTRAINT app_postulados8_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.app_menu
(
    id bigint NOT NULL DEFAULT nextval('app_menu_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(100) COLLATE pg_catalog."default" NOT NULL,
    valor integer NOT NULL,
    categoria_id bigint,
    restaurante_id integer,
    foto character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT app_menu_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_categoria
(
    id bigint NOT NULL DEFAULT nextval('app_categoria_id_seq'::regclass),
    nombre character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT app_categoria_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_pedido
(
    id bigint NOT NULL DEFAULT nextval('app_pedido_id_seq'::regclass),
    estado character varying(2) COLLATE pg_catalog."default" NOT NULL,
    fecha date NOT NULL,
    mesa_id bigint,
    restaurante_id integer,
    CONSTRAINT app_pedido_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_destallepedido
(
    id bigint NOT NULL DEFAULT nextval('app_destallepedido_id_seq'::regclass),
    cantidad integer NOT NULL,
    valor_unitario integer NOT NULL,
    articulo_id bigint,
    pedido_id bigint,
    CONSTRAINT app_destallepedido_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_factura
(
    id bigint NOT NULL DEFAULT nextval('app_factura_id_seq'::regclass),
    total integer NOT NULL,
    fecha date NOT NULL,
    mesero_id character varying(12) COLLATE pg_catalog."default",
    pedido_id bigint,
    restaurante_id integer,
    CONSTRAINT app_factura_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.app_contacto
(
    id bigint NOT NULL DEFAULT nextval('app_contacto_id_seq'::regclass),
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    mensaje character varying(500) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT app_contacto_pkey PRIMARY KEY (id)
);




CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL DEFAULT nextval('auth_group_id_seq'::regclass),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL DEFAULT nextval('auth_group_permissions_id_seq'::regclass),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL DEFAULT nextval('auth_permission_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL DEFAULT nextval('auth_user_id_seq'::regclass),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL DEFAULT nextval('auth_user_groups_id_seq'::regclass),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL DEFAULT nextval('auth_user_user_permissions_id_seq'::regclass),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL DEFAULT nextval('django_admin_log_id_seq'::regclass),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL DEFAULT nextval('django_content_type_id_seq'::regclass),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL DEFAULT nextval('django_migrations_id_seq'::regclass),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

ALTER TABLE IF EXISTS public.app_caja
    ADD CONSTRAINT app_caja_restaurante_id_5eb98a43_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_caja_restaurante_id_5eb98a43
    ON public.app_caja(restaurante_id);


ALTER TABLE IF EXISTS public.app_cocina
    ADD CONSTRAINT app_cocina_restaurante_id_d979c020_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_cocina_restaurante_id_d979c020
    ON public.app_cocina(restaurante_id);


ALTER TABLE IF EXISTS public.app_destallepedido
    ADD CONSTRAINT app_destallepedido_articulo_id_7c34fabc_fk_app_menu_id FOREIGN KEY (articulo_id)
    REFERENCES public.app_menu (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_destallepedido_articulo_id_7c34fabc
    ON public.app_destallepedido(articulo_id);


ALTER TABLE IF EXISTS public.app_destallepedido
    ADD CONSTRAINT app_destallepedido_pedido_id_ca110609_fk_app_pedido_id FOREIGN KEY (pedido_id)
    REFERENCES public.app_pedido (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_destallepedido_pedido_id_ca110609
    ON public.app_destallepedido(pedido_id);


ALTER TABLE IF EXISTS public.app_estado
    ADD CONSTRAINT app_estado_mesero_id_b92455ea_fk_app_mesero_documento FOREIGN KEY (mesero_id)
    REFERENCES public.app_mesero (documento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_estado_mesero_id_b92455ea
    ON public.app_estado(mesero_id);


ALTER TABLE IF EXISTS public.app_estado
    ADD CONSTRAINT app_estado_restaurante_id_88c8c15d_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_estado_restaurante_id_88c8c15d
    ON public.app_estado(restaurante_id);


ALTER TABLE IF EXISTS public.app_factura
    ADD CONSTRAINT app_factura_mesero_id_0188bbce_fk_app_mesero_documento FOREIGN KEY (mesero_id)
    REFERENCES public.app_mesero (documento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_factura_mesero_id_0188bbce_like
    ON public.app_factura(mesero_id);


ALTER TABLE IF EXISTS public.app_factura
    ADD CONSTRAINT app_factura_pedido_id_75fb7568_fk_app_pedido_id FOREIGN KEY (pedido_id)
    REFERENCES public.app_pedido (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_factura_pedido_id_75fb7568
    ON public.app_factura(pedido_id);


ALTER TABLE IF EXISTS public.app_factura
    ADD CONSTRAINT app_factura_restaurante_id_d83e2281_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_factura_restaurante_id_d83e2281
    ON public.app_factura(restaurante_id);


ALTER TABLE IF EXISTS public.app_menu
    ADD CONSTRAINT app_menu_categoria_id_7f6e91c3_fk_app_categoria_id FOREIGN KEY (categoria_id)
    REFERENCES public.app_categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_menu_categoria_id_7f6e91c3
    ON public.app_menu(categoria_id);


ALTER TABLE IF EXISTS public.app_menu
    ADD CONSTRAINT app_menu_restaurante_id_06858e12_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_menu_restaurante_id_06858e12
    ON public.app_menu(restaurante_id);


ALTER TABLE IF EXISTS public.app_mesas
    ADD CONSTRAINT app_mesas_restaurante_id_46cbb288_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_mesas_restaurante_id_46cbb288
    ON public.app_mesas(restaurante_id);


ALTER TABLE IF EXISTS public.app_mesero
    ADD CONSTRAINT app_mesero_departamento_id_9a9008cd_fk_app_departamento_id FOREIGN KEY (departamento_id)
    REFERENCES public.app_departamento (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_mesero_departamento_id_9a9008cd
    ON public.app_mesero(departamento_id);


ALTER TABLE IF EXISTS public.app_mesero
    ADD CONSTRAINT app_mesero_municipio_id_955f5342_fk_app_municipio_id FOREIGN KEY (municipio_id)
    REFERENCES public.app_municipio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_mesero_municipio_id_955f5342
    ON public.app_mesero(municipio_id);


ALTER TABLE IF EXISTS public.app_oferta
    ADD CONSTRAINT app_oferta_restaurante_id_7b92efe0_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_oferta_restaurante_id_7b92efe0
    ON public.app_oferta(restaurante_id);


ALTER TABLE IF EXISTS public.app_pedido
    ADD CONSTRAINT app_pedido_mesa_id_b87550d4_fk_app_mesas_id FOREIGN KEY (mesa_id)
    REFERENCES public.app_mesas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_pedido_mesa_id_b87550d4
    ON public.app_pedido(mesa_id);


ALTER TABLE IF EXISTS public.app_pedido
    ADD CONSTRAINT app_pedido_restaurante_id_1dbba5ec_fk_app_restaurante_nit FOREIGN KEY (restaurante_id)
    REFERENCES public.app_restaurante (nit) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_pedido_restaurante_id_1dbba5ec
    ON public.app_pedido(restaurante_id);


ALTER TABLE IF EXISTS public.app_postulados
    ADD CONSTRAINT app_postulados8_mesero_id_531ef682_fk_app_mesero_documento FOREIGN KEY (mesero_id)
    REFERENCES public.app_mesero (documento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_postulados8_mesero_id_531ef682
    ON public.app_postulados(mesero_id);


ALTER TABLE IF EXISTS public.app_postulados
    ADD CONSTRAINT app_postulados8_oferta_id_f5b4d105_fk_app_oferta_id FOREIGN KEY (oferta_id)
    REFERENCES public.app_oferta (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_postulados8_oferta_id_f5b4d105
    ON public.app_postulados(oferta_id);


ALTER TABLE IF EXISTS public.app_restaurante
    ADD CONSTRAINT app_restaurante_departamento_id_967ea043_fk_app_departamento_id FOREIGN KEY (departamento_id)
    REFERENCES public.app_departamento (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_restaurante_departamento_id_967ea043
    ON public.app_restaurante(departamento_id);


ALTER TABLE IF EXISTS public.app_restaurante
    ADD CONSTRAINT app_restaurante_municipio_id_b4b062da_fk_app_municipio_id FOREIGN KEY (municipio_id)
    REFERENCES public.app_municipio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS app_restaurante_municipio_id_b4b062da
    ON public.app_restaurante(municipio_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);

END;
